/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParameterSetup_JDialog.java
 *
 * Created on Nov 14, 2011, 2:17:06 PM
 */
package deconvolutionapp;

import javax.swing.JOptionPane;


/**
 *
 * @author Gregory
 */
public class ParameterSetup_JDialog extends javax.swing.JDialog {

    //Class Variables
    protected Boolean OKflag;
    protected Double MZValue_Observation;
    protected Double MZRange_Observation;
    protected ConfigReader ConfigFile;
    
    public ParameterSetup_JDialog(java.awt.Frame parent, ConfigReader ConfigFile,boolean modal){
        super(parent, modal);
        initComponents();
    }
    
    /** Creates new form ParameterSetup_JDialog */
    public ParameterSetup_JDialog(  java.awt.Frame parent,
                                    ConfigReader ConfigFile,
                                    boolean modal,
                                    Double MZValue_Observation,
                                    Double MZRange_Observation) {
        super(parent, modal);
        initComponents();
        
        //This ConfigFile Reference
        this.ConfigFile = ConfigFile;
        
        //Validation flag
        this.OKflag = new Boolean(false);
        this.MZValue_Observation = MZValue_Observation;
        this.MZRange_Observation = MZRange_Observation;
        
        //Text Boxes
        MZValue_Observation_field.setText(String.format("%.2f", MZValue_Observation));
        MZRange_Observation_Field.setText(String.format("%.2f", MZRange_Observation));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        EpsilonBallGroup = new javax.swing.ButtonGroup();
        ParameterPanel = new javax.swing.JPanel();
        TabPanel = new javax.swing.JTabbedPane();
        MethodsTab = new javax.swing.JPanel();
        LS_CheckBox = new javax.swing.JCheckBox();
        ML_CheckBox = new javax.swing.JCheckBox();
        MMV_CheckBox = new javax.swing.JCheckBox();
        RunName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ConvolutionKernelName_field = new javax.swing.JTextField();
        MZValue_Observation_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MZRange_Observation_Field = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        KernelDirectory = new javax.swing.JButton();
        ISTA_CheckBox = new javax.swing.JCheckBox();
        LS_Tab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LS_NumIterations = new javax.swing.JTextField();
        ML_Tab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ML_NumIterations = new javax.swing.JTextField();
        ISTA_Tab = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ISTA_NumIterations = new javax.swing.JTextField();
        ISTA_Lagrangian = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MMV_Tab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MMV_NumIterations = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EpsilonBallPercentile_Radio = new javax.swing.JRadioButton();
        EpsilonBallFixed_Radio = new javax.swing.JRadioButton();
        MMV_LagrangianMIN = new javax.swing.JTextField();
        MMV_LagrangianMAX = new javax.swing.JTextField();
        MMV_Lagrangian_Num_Iter = new javax.swing.JTextField();
        MMV_EpsilonBallPercentile = new javax.swing.JTextField();
        MMV_EpsilonBallFixedValue = new javax.swing.JTextField();
        ButtonPanel = new javax.swing.JPanel();
        RunButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(deconvolutionapp.DeConvolutionApp_RevD.class).getContext().getResourceMap(ParameterSetup_JDialog.class);
        ParameterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("ParameterPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("ParameterPanel.border.titleFont"))); // NOI18N
        ParameterPanel.setName("ParameterPanel"); // NOI18N

        TabPanel.setBackground(resourceMap.getColor("TabPanel.background")); // NOI18N
        TabPanel.setName("TabPanel"); // NOI18N

        MethodsTab.setBackground(resourceMap.getColor("MethodsTab.background")); // NOI18N
        MethodsTab.setName("MethodsTab"); // NOI18N

        LS_CheckBox.setBackground(resourceMap.getColor("LS_CheckBox.background")); // NOI18N
        LS_CheckBox.setText(resourceMap.getString("LS_CheckBox.text")); // NOI18N
        LS_CheckBox.setName("LS_CheckBox"); // NOI18N

        ML_CheckBox.setBackground(resourceMap.getColor("ML_CheckBox.background")); // NOI18N
        ML_CheckBox.setText(resourceMap.getString("ML_CheckBox.text")); // NOI18N
        ML_CheckBox.setName("ML_CheckBox"); // NOI18N

        MMV_CheckBox.setBackground(resourceMap.getColor("MMV_CheckBox.background")); // NOI18N
        MMV_CheckBox.setText(resourceMap.getString("MMV_CheckBox.text")); // NOI18N
        MMV_CheckBox.setName("MMV_CheckBox"); // NOI18N

        RunName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RunName.setText(resourceMap.getString("RunName.text")); // NOI18N
        RunName.setName("RunName"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        ConvolutionKernelName_field.setEditable(false);
        ConvolutionKernelName_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ConvolutionKernelName_field.setText(resourceMap.getString("ConvolutionKernelName_field.text")); // NOI18N
        ConvolutionKernelName_field.setToolTipText(resourceMap.getString("ConvolutionKernelName_field.toolTipText")); // NOI18N
        ConvolutionKernelName_field.setName("ConvolutionKernelName_field"); // NOI18N

        MZValue_Observation_field.setText(resourceMap.getString("MZValue_Observation_field.text")); // NOI18N
        MZValue_Observation_field.setName("MZValue_Observation_field"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        MZRange_Observation_Field.setName("MZRange_Observation_Field"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        KernelDirectory.setFont(resourceMap.getFont("KernelDirectory.font")); // NOI18N
        KernelDirectory.setText(resourceMap.getString("KernelDirectory.text")); // NOI18N
        KernelDirectory.setName("KernelDirectory"); // NOI18N
        KernelDirectory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KernelDirectoryMouseClicked(evt);
            }
        });

        ISTA_CheckBox.setBackground(resourceMap.getColor("ISTA_CheckBox.background")); // NOI18N
        ISTA_CheckBox.setText(resourceMap.getString("ISTA_CheckBox.text")); // NOI18N
        ISTA_CheckBox.setName("ISTA_CheckBox"); // NOI18N

        javax.swing.GroupLayout MethodsTabLayout = new javax.swing.GroupLayout(MethodsTab);
        MethodsTab.setLayout(MethodsTabLayout);
        MethodsTabLayout.setHorizontalGroup(
            MethodsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MethodsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MethodsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MMV_CheckBox)
                    .addComponent(jLabel9)
                    .addComponent(ML_CheckBox)
                    .addGroup(MethodsTabLayout.createSequentialGroup()
                        .addGroup(MethodsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MethodsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MethodsTabLayout.createSequentialGroup()
                                .addComponent(ConvolutionKernelName_field, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(KernelDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MethodsTabLayout.createSequentialGroup()
                                .addComponent(MZValue_Observation_field, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MZRange_Observation_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addComponent(LS_CheckBox)
                    .addGroup(MethodsTabLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33))
                    .addComponent(RunName, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(ISTA_CheckBox))
                .addContainerGap())
        );
        MethodsTabLayout.setVerticalGroup(
            MethodsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MethodsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MethodsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ConvolutionKernelName_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KernelDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MethodsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(MZValue_Observation_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(MZRange_Observation_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LS_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ML_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ISTA_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MMV_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RunName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabPanel.addTab(resourceMap.getString("MethodsTab.TabConstraints.tabTitle"), MethodsTab); // NOI18N

        LS_Tab.setBackground(resourceMap.getColor("LS_Tab.background")); // NOI18N
        LS_Tab.setName("LS_Tab"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, LS_CheckBox, org.jdesktop.beansbinding.ELProperty.create("${selected}"), LS_Tab, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        LS_NumIterations.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LS_NumIterations.setText(resourceMap.getString("LS_NumIterations.text")); // NOI18N
        LS_NumIterations.setToolTipText(resourceMap.getString("LS_NumIterations.toolTipText")); // NOI18N
        LS_NumIterations.setName("LS_NumIterations"); // NOI18N

        javax.swing.GroupLayout LS_TabLayout = new javax.swing.GroupLayout(LS_Tab);
        LS_Tab.setLayout(LS_TabLayout);
        LS_TabLayout.setHorizontalGroup(
            LS_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LS_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LS_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        LS_TabLayout.setVerticalGroup(
            LS_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LS_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LS_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LS_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        TabPanel.addTab(resourceMap.getString("LS_Tab.TabConstraints.tabTitle"), LS_Tab); // NOI18N

        ML_Tab.setBackground(resourceMap.getColor("ML_Tab.background")); // NOI18N
        ML_Tab.setName("ML_Tab"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ML_CheckBox, org.jdesktop.beansbinding.ELProperty.create("${selected}"), ML_Tab, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        ML_NumIterations.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ML_NumIterations.setText(resourceMap.getString("ML_NumIterations.text")); // NOI18N
        ML_NumIterations.setToolTipText(resourceMap.getString("ML_NumIterations.toolTipText")); // NOI18N
        ML_NumIterations.setName("ML_NumIterations"); // NOI18N

        javax.swing.GroupLayout ML_TabLayout = new javax.swing.GroupLayout(ML_Tab);
        ML_Tab.setLayout(ML_TabLayout);
        ML_TabLayout.setHorizontalGroup(
            ML_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ML_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ML_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        ML_TabLayout.setVerticalGroup(
            ML_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ML_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ML_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ML_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        TabPanel.addTab(resourceMap.getString("ML_Tab.TabConstraints.tabTitle"), ML_Tab); // NOI18N

        ISTA_Tab.setBackground(resourceMap.getColor("ISTA_Tab.background")); // NOI18N
        ISTA_Tab.setName("ISTA_Tab"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        ISTA_NumIterations.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ISTA_NumIterations.setText(resourceMap.getString("ISTA_NumIterations.text")); // NOI18N
        ISTA_NumIterations.setToolTipText(resourceMap.getString("ISTA_NumIterations.toolTipText")); // NOI18N
        ISTA_NumIterations.setName("ISTA_NumIterations"); // NOI18N

        ISTA_Lagrangian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ISTA_Lagrangian.setText(resourceMap.getString("ISTA_Lagrangian.text")); // NOI18N
        ISTA_Lagrangian.setToolTipText(resourceMap.getString("ISTA_Lagrangian.toolTipText")); // NOI18N
        ISTA_Lagrangian.setName("ISTA_Lagrangian"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        javax.swing.GroupLayout ISTA_TabLayout = new javax.swing.GroupLayout(ISTA_Tab);
        ISTA_Tab.setLayout(ISTA_TabLayout);
        ISTA_TabLayout.setHorizontalGroup(
            ISTA_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ISTA_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ISTA_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ISTA_TabLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ISTA_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ISTA_TabLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ISTA_Lagrangian, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        ISTA_TabLayout.setVerticalGroup(
            ISTA_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ISTA_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ISTA_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ISTA_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ISTA_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ISTA_Lagrangian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        TabPanel.addTab(resourceMap.getString("ISTA_Tab.TabConstraints.tabTitle"), ISTA_Tab); // NOI18N

        MMV_Tab.setBackground(resourceMap.getColor("MMV_Tab.background")); // NOI18N
        MMV_Tab.setName("MMV_Tab"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, MMV_CheckBox, org.jdesktop.beansbinding.ELProperty.create("${selected}"), MMV_Tab, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        MMV_NumIterations.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MMV_NumIterations.setText(resourceMap.getString("MMV_NumIterations.text")); // NOI18N
        MMV_NumIterations.setToolTipText(resourceMap.getString("MMV_NumIterations.toolTipText")); // NOI18N
        MMV_NumIterations.setName("MMV_NumIterations"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        EpsilonBallPercentile_Radio.setBackground(resourceMap.getColor("EpsilonBallPercentile_Radio.background")); // NOI18N
        EpsilonBallGroup.add(EpsilonBallPercentile_Radio);
        EpsilonBallPercentile_Radio.setSelected(true);
        EpsilonBallPercentile_Radio.setText(resourceMap.getString("EpsilonBallPercentile_Radio.text")); // NOI18N
        EpsilonBallPercentile_Radio.setName("EpsilonBallPercentile_Radio"); // NOI18N

        EpsilonBallFixed_Radio.setBackground(resourceMap.getColor("EpsilonBallFixed_Radio.background")); // NOI18N
        EpsilonBallGroup.add(EpsilonBallFixed_Radio);
        EpsilonBallFixed_Radio.setText(resourceMap.getString("EpsilonBallFixed_Radio.text")); // NOI18N
        EpsilonBallFixed_Radio.setName("EpsilonBallFixed_Radio"); // NOI18N

        MMV_LagrangianMIN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MMV_LagrangianMIN.setText(resourceMap.getString("MMV_LagrangianMIN.text")); // NOI18N
        MMV_LagrangianMIN.setToolTipText(resourceMap.getString("MMV_LagrangianMIN.toolTipText")); // NOI18N
        MMV_LagrangianMIN.setName("MMV_LagrangianMIN"); // NOI18N

        MMV_LagrangianMAX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MMV_LagrangianMAX.setText(resourceMap.getString("MMV_LagrangianMAX.text")); // NOI18N
        MMV_LagrangianMAX.setToolTipText(resourceMap.getString("MMV_LagrangianMAX.toolTipText")); // NOI18N
        MMV_LagrangianMAX.setName("MMV_LagrangianMAX"); // NOI18N

        MMV_Lagrangian_Num_Iter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MMV_Lagrangian_Num_Iter.setText(resourceMap.getString("MMV_Lagrangian_Num_Iter.text")); // NOI18N
        MMV_Lagrangian_Num_Iter.setToolTipText(resourceMap.getString("MMV_Lagrangian_Num_Iter.toolTipText")); // NOI18N
        MMV_Lagrangian_Num_Iter.setName("MMV_Lagrangian_Num_Iter"); // NOI18N

        MMV_EpsilonBallPercentile.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MMV_EpsilonBallPercentile.setText(resourceMap.getString("MMV_EpsilonBallPercentile.text")); // NOI18N
        MMV_EpsilonBallPercentile.setToolTipText(resourceMap.getString("MMV_EpsilonBallPercentile.toolTipText")); // NOI18N
        MMV_EpsilonBallPercentile.setName("MMV_EpsilonBallPercentile"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, EpsilonBallPercentile_Radio, org.jdesktop.beansbinding.ELProperty.create("${selected}"), MMV_EpsilonBallPercentile, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        MMV_EpsilonBallFixedValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MMV_EpsilonBallFixedValue.setText(resourceMap.getString("MMV_EpsilonBallFixedValue.text")); // NOI18N
        MMV_EpsilonBallFixedValue.setToolTipText(resourceMap.getString("MMV_EpsilonBallFixedValue.toolTipText")); // NOI18N
        MMV_EpsilonBallFixedValue.setName("MMV_EpsilonBallFixedValue"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, EpsilonBallFixed_Radio, org.jdesktop.beansbinding.ELProperty.create("${selected}"), MMV_EpsilonBallFixedValue, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout MMV_TabLayout = new javax.swing.GroupLayout(MMV_Tab);
        MMV_Tab.setLayout(MMV_TabLayout);
        MMV_TabLayout.setHorizontalGroup(
            MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MMV_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(EpsilonBallPercentile_Radio)
                    .addComponent(EpsilonBallFixed_Radio))
                .addGap(18, 18, 18)
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MMV_EpsilonBallFixedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MMV_EpsilonBallPercentile, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MMV_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MMV_LagrangianMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MMV_LagrangianMAX, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MMV_Lagrangian_Num_Iter, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        MMV_TabLayout.setVerticalGroup(
            MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MMV_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MMV_NumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MMV_LagrangianMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MMV_LagrangianMAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(MMV_Lagrangian_Num_Iter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EpsilonBallPercentile_Radio)
                    .addComponent(MMV_EpsilonBallPercentile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MMV_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EpsilonBallFixed_Radio)
                    .addComponent(MMV_EpsilonBallFixedValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        TabPanel.addTab(resourceMap.getString("MMV_Tab.TabConstraints.tabTitle"), MMV_Tab); // NOI18N

        javax.swing.GroupLayout ParameterPanelLayout = new javax.swing.GroupLayout(ParameterPanel);
        ParameterPanel.setLayout(ParameterPanelLayout);
        ParameterPanelLayout.setHorizontalGroup(
            ParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParameterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        ParameterPanelLayout.setVerticalGroup(
            ParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParameterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        ButtonPanel.setName("ButtonPanel"); // NOI18N

        RunButton.setText(resourceMap.getString("RunButton.text")); // NOI18N
        RunButton.setName("RunButton"); // NOI18N
        RunButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RunButtonMouseClicked(evt);
            }
        });

        CancelButton.setText(resourceMap.getString("CancelButton.text")); // NOI18N
        CancelButton.setName("CancelButton"); // NOI18N
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(RunButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ParameterPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParameterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
    public String getRunName() throws Exception{
        
        if (this.OKflag){
            return RunName.getText();
        }
        else{
            throw new Exception("RunParameter Setup Canceled");
        }
        
    }
    
    private void RunButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunButtonMouseClicked
        
        //Save the Configurations to a Recipe XML Document
        if(!RunName.getText().isEmpty()){
            
            try{
                String LastDir = ConfigFile.getConfigParameter("/root/LastOpenedDirectory");
                XML_FileSaver handler = new XML_FileSaver(LastDir,"RunParameters");

                //Pass all of the configurations to save
                handler.saveParameterEntry(
                                            RunName.getText(),
                                            ConvolutionKernelName_field.getText(),
                                            MZValue_Observation,
                                            MZRange_Observation,
                                            LS_CheckBox.isSelected(),
                                            ML_CheckBox.isSelected(),
                                            ISTA_CheckBox.isSelected(),
                                            MMV_CheckBox.isSelected(),
                                            Integer.parseInt(LS_NumIterations.getText()),
                                            Integer.parseInt(ML_NumIterations.getText()),
                                            Integer.parseInt(ISTA_NumIterations.getText()),
                                            Integer.parseInt(MMV_NumIterations.getText()),
                                            Double.parseDouble(ISTA_Lagrangian.getText()),
                                            Double.parseDouble(MMV_LagrangianMIN.getText()),
                                            Double.parseDouble(MMV_LagrangianMAX.getText()),
                                            Integer.parseInt(MMV_Lagrangian_Num_Iter.getText()),
                                            EpsilonBallPercentile_Radio.isSelected(),
                                            EpsilonBallFixed_Radio.isSelected(),
                                            Double.parseDouble(MMV_EpsilonBallPercentile.getText()),
                                            Double.parseDouble(MMV_EpsilonBallFixedValue.getText())
                                            );

                //Trash the Handler and run gc()
                handler = null;
                
                this.OKflag = true;
                
                //Return control back to the main_Frame.java
                this.setVisible(false);
            }
            catch (Exception ex){
                ex.printStackTrace();
            }
            finally{
                System.gc();
            }
  
        }
        else{
            //custom title, error icon
            JOptionPane.showMessageDialog(this,
                "Please Enter a name for the Run, in the Methods Tab",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_RunButtonMouseClicked

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        
        this.OKflag = false;
        this.setVisible(false);
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void KernelDirectoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KernelDirectoryMouseClicked
        
        ConvolutionLoader_JDialog ConvolutionLoader = new ConvolutionLoader_JDialog(null,ConfigFile,true);
        
        //Show the frame
        ConvolutionLoader.setVisible(true);
            
        //waits till close
        
        //Now try and get the result
        try{  
            ConvolutionKernelName_field.setText(ConvolutionLoader.getSelectedKernel());
        }
        catch (Exception ex){
            ex.printStackTrace();
        }
        finally{
            ConvolutionLoader = null;
        }
    }//GEN-LAST:event_KernelDirectoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParameterSetup_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParameterSetup_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParameterSetup_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParameterSetup_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ParameterSetup_JDialog dialog = new ParameterSetup_JDialog(new javax.swing.JFrame(),new ConfigReader(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField ConvolutionKernelName_field;
    private javax.swing.JRadioButton EpsilonBallFixed_Radio;
    private javax.swing.ButtonGroup EpsilonBallGroup;
    private javax.swing.JRadioButton EpsilonBallPercentile_Radio;
    private javax.swing.JCheckBox ISTA_CheckBox;
    private javax.swing.JTextField ISTA_Lagrangian;
    private javax.swing.JTextField ISTA_NumIterations;
    private javax.swing.JPanel ISTA_Tab;
    private javax.swing.JButton KernelDirectory;
    private javax.swing.JCheckBox LS_CheckBox;
    private javax.swing.JTextField LS_NumIterations;
    private javax.swing.JPanel LS_Tab;
    private javax.swing.JCheckBox ML_CheckBox;
    private javax.swing.JTextField ML_NumIterations;
    private javax.swing.JPanel ML_Tab;
    private javax.swing.JCheckBox MMV_CheckBox;
    private javax.swing.JTextField MMV_EpsilonBallFixedValue;
    private javax.swing.JTextField MMV_EpsilonBallPercentile;
    private javax.swing.JTextField MMV_LagrangianMAX;
    private javax.swing.JTextField MMV_LagrangianMIN;
    private javax.swing.JTextField MMV_Lagrangian_Num_Iter;
    private javax.swing.JTextField MMV_NumIterations;
    private javax.swing.JPanel MMV_Tab;
    private javax.swing.JTextField MZRange_Observation_Field;
    private javax.swing.JTextField MZValue_Observation_field;
    private javax.swing.JPanel MethodsTab;
    private javax.swing.JPanel ParameterPanel;
    private javax.swing.JButton RunButton;
    private javax.swing.JTextField RunName;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
